name: release
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
env:
  APP_NAME: 'groovebox'
  NIM_VERSION: 'stable'
  MAINTAINER: 'OpenPeeps'
jobs:
  build-artifact:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          # - os: ubuntu-latest
          #   arch: arm64
          - os: macos-14
            arch: x86_64
          # - os: macos-14
          #   arch: arm64
    steps:
      - uses: actions/checkout@v4
      # Optional: Cache nimble packages for faster builds
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v4
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-v2-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-v2-
        if: runner.os != 'Windows'
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ env.NIM_VERSION }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup MacPorts (macOS only)
        if: runner.os == 'macOS'
        uses: melusina-org/setup-macports@v1
      - name: Install C library dependencies
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends \
              pkg-config libssl-dev libevent-dev ca-certificates libpcre3-dev
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            sudo port -v selfupdate
            sudo port install pkgconfig openssl libevent pcre
          fi
        shell: bash
      - run: nimble build -Y -d:release
      - name: Create artifact
        run: |
          os="${{ runner.os }}"
          arch="${{ matrix.arch }}"
          suffix="$os${arch:+-$arch}"
          assets="${{ env.APP_NAME }}_${suffix,,}"
          echo "$assets"
          mkdir -p "dist/$assets"
          cp -r bin LICENSE README.* "dist/$assets/"
          (
            cd dist
            if [[ "${{ runner.os }}" == Windows ]]; then
              7z a "$assets.zip" "$assets"
            else
              tar czf "$assets.tar.gz" "$assets"
            fi
            ls -lah *.*
          )
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}${{ matrix.arch && format('-{0}', matrix.arch) || '' }}
          path: |
            dist/*.tar.gz
            dist/*.zip

  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
      - build-artifact
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: Release
          draft: false
          prerelease: false

      - name: Write upload_url to file
        run: echo '${{ steps.create-release.outputs.upload_url }}' > upload_url.txt

      - uses: actions/upload-artifact@v4
        with:
          name: create-release
          path: upload_url.txt

  upload-release:
    if: startsWith(github.ref, 'refs/tags/') # Only run this job for tag pushes
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            asset_name_suffix: linux-x86_64.tar.gz
            asset_content_type: application/gzip
          # - os: ubuntu-latest
          #   arch: arm64
          #   asset_name_suffix: linux-arm64.tar.gz
          #   asset_content_type: application/gzip
          - os: macos-14
            arch: x86_64
            asset_name_suffix: macos-x86_64.tar.gz
            asset_content_type: application/gzip
          # - os: macos-14
          #   arch: arm64
          #   asset_name_suffix: macos-arm64.tar.gz
          #   asset_content_type: application/gzip
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact-${{ matrix.os }}${{ matrix.arch && format('-{0}', matrix.arch) || '' }}

      - uses: actions/download-artifact@v4
        with:
          name: create-release

      - id: vars
        run: |
          echo "upload_url=$(cat upload_url.txt)" >> $GITHUB_OUTPUT

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.vars.outputs.upload_url }}
          asset_path: dist/${{ env.APP_NAME }}_${{ matrix.asset_name_suffix }}
          asset_name: ${{ env.APP_NAME }}_${{ matrix.asset_name_suffix }}
          asset_content_type: ${{ matrix.asset_content_type }}